#!/bin/bash

echo 'Exporting required environment variables'
export COMPOSER_HOME="$OPENSHIFT_DATA_DIR/.composer"

if [ ! -f "$OPENSHIFT_DATA_DIR/composer.phar" ]; then
    echo 'Installing Composer'
    curl -s https://getcomposer.org/installer | php -- --quiet --install-dir=$OPENSHIFT_DATA_DIR
else
    echo 'Updating Composer'
    php $OPENSHIFT_DATA_DIR/composer.phar -q --no-ansi self-update
fi

echo 'Copying over the configuration' ; cd $OPENSHIFT_REPO_DIR/app && rm -rf config && cp -r $OPENSHIFT_DATA_DIR/config .

if [ -d "$OPENSHIFT_REPO_DIR/vendor" ]; then
    echo 'Laravel dependencies already installed, Moving on...'
else
    echo 'Hang in there, we are getting ready to Install/Update Laravel dependencies'
    # Uncomment to activate composer install for Laravel on Git Push
    ( echo 'Installing/Updating Laravel'; unset GIT_DIR ; cd $OPENSHIFT_REPO_DIR ; php $OPENSHIFT_DATA_DIR/composer.phar -q --no-ansi install )
fi

echo 'Updating symlinks for data directories' ; cd $OPENSHIFT_REPO_DIR/public/images && rm -f profile_photos && ln -sf $OPENSHIFT_DATA_DIR/profile_photos .

echo 'Performing database migration' ; cd $OPENSHIFT_REPO_DIR && php artisan migrate
